from typing import Protocol, List, Dict, Any

# Protocol defining the required blockchain interface
class Chain(Protocol):
    def append_event(self, event: Dict[str, Any]) -> str: ...
    def get_events(self) -> List[Dict[str, Any]]: ...
    def verify_chain(self) -> bool: ...
